name: learn_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  avatar_glow: ^2.0.2
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.2
  faker: ^2.0.0
  get: ^4.6.5
  http: ^0.13.5
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  lottie: ^1.4.1
  carousel_slider: 4.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/icons/icon.png
  web: 
    image_path: path/to/icon.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
    generate: true
  windows: 
    image_path: path/to/icon.png
    generate: true
    icon_size: 48
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/images/
    - assets/lotties/
  uses-material-design: true

